Repository clubgamma/Weather-Web-App-2024, pull requests merged in 2024-10, with the labels that each got.

#14 JS Logic Added
  index.html
  index.js
  weather_info.html
Labels: good first issue, hacktoberfest-accepted, level 2

#21 Forecast cards(html css)
  css/style.css
  weather_info.html
Labels: level 1, hacktoberfest-accepted

#25 Bug Fixes and Real Time Data Visible
  css/style.css
  index.js
Labels: enhancement, hacktoberfest-accepted, level 2

#26 Feature: Search suggestions
  css/style.css
  index.html
  index.js
Labels: enhancement, hacktoberfest-accepted, level 2

#33 removing scrollbar and add some colors for weather-icon
  css/style.css
  weather_info.html
Labels: enhancement, level 1, hacktoberfest-accepted

#30 bug: in search box by
  index.js
Labels: bug, enhancement, level 1, hacktoberfest-accepted

#38 Added Search Icon and Fix Size Issue..
  css/style.css
  index.html
  index.js
Labels: enhancement, level 1, hacktoberfest-accepted

#49 added ui element to show the error
  css/style.css
  index.html
  index.js
Labels: enhancement, level 1, hacktoberfest-accepted

#47 Feat/Graph add
  chart.js
  index.html
  weather_info.html
Labels: enhancement, hacktoberfest-accepted, level 2

#52 🌍 Implement Accurate Current Location Weather Detection Feature
  css/style.css
  index.html
  index.js
Labels: enhancement, hacktoberfest-accepted, level 2

#53 Add Wind Speed and Humidity to Weather Data
  css/information.css
  index.js
  weather_info.html
Labels: enhancement, hacktoberfest-accepted, level 2

#59 Add Air Quality Index
  css/information.css
  index.js
  weather_info.html
Labels: enhancement, level 1, hacktoberfest-accepted

#58 access search suggestions using up/down keys
  index.html
  index.js
Labels: enhancement, hacktoberfest-accepted, level 2

#65 Updated Images
  css/information.css
  images/clear-sky.png
  images/cloud-sun.png
  images/mist.png
  images/partial-cloud.png
  images/rainChance.png
  images/rainy.png
  images/scatter-clouds.png
  images/shower-rain.png
  images/snow.png
  images/stormy.png
  index.js
  weather_info.html
Labels: enhancement, level 1, hacktoberfest-accepted

#79 Implement Weather Map & Wind Direction Indicator
  css/information.css
  index.js
  weather_info.html
  weathermap.js
Labels: bug, enhancement, hacktoberfest-accepted, level 3, urgent

#89 Includes All The Changes
  css/information.css
  images/sunrise.png
  images/sunset.png
  index.js
  weather_info.html
Labels: enhancement, hacktoberfest-accepted, level 3

#91 Add feat/map
  css/information.css
  index.js
  map.js
  weather_info.html
Labels: enhancement, hacktoberfest-accepted, level 2
